Repository afreakyelf/Pdf-Viewer, pull requests merged in 2025-01, with the labels that each got.

#132 refactor: split PdfRendererViewCompose into overloaded functions for varied sources
  README.md
  app/src/main/java/com/rajat/sample/pdfviewer/ComposeActivity.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/compose/PdfRendererCompose.kt
Labels: Stale, size/L

#134 Added Dispatchers.Main coroutine scope when invoking listener.onDownloadStart()
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfDownloader.kt
Labels: size/XS, Stale

#141 Remove unused pdf engine
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfViewerActivity.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/util/PdfEngine.kt
  pdfViewer/src/main/res/values/attrs.xml
Labels: size/S

#144 Remove force unwrap
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererCore.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/util/FileUtils.kt
Labels: size/S

#149 Fix x and y translation issue on double tap
  pdfViewer/src/main/java/com/rajat/pdfviewer/PinchZoomRecyclerView.kt
Labels: size/XS
