Repository afreakyelf/Pdf-Viewer, pull requests merged in 2025-04, with the labels that each got.

#188 fix: ensure PdfRendererView always releases resources via onDetachedFromWindow
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
Labels: size/XS

#185 updated README.md by adding min/complie sdk versions description
  README.md
Labels: size/XS

#130 handle file can not be opened because of pdf contains password
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
Labels: size/XS, Stale

#135 adjust Composable function signature to make source mandatory
  README.md
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfSource.kt
  pdfViewer/src/main/res/layout/activity_pdf_viewer.xml
Labels: Stale, size/M
