Repository afreakyelf/Pdf-Viewer, pull requests merged in 2025-05, with the labels that each got.

#195 Make cache identifier for local file more unique
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
Labels: size/XS

#196 Fixed Coroutines memory leak
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererCore.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfViewAdapter.kt
Labels: size/M

#198 Kotlin 2.1.20 & AGP 8.9.2
  app/build.gradle.kts
  app/src/main/java/com/rajat/sample/pdfviewer/ComposeActivity.kt
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  pdfViewer/build.gradle.kts
  pdfViewer/src/main/java/com/rajat/pdfviewer/compose/PdfRendererCompose.kt
Labels: size/L

#199 Clear cache dir
  pdfViewer/src/main/java/com/rajat/pdfviewer/util/CacheManager.kt
Labels: size/XS

#204 Fix: Add missing default implementation for `onPdfRenderStart` in StatusCallBack
  pdfViewer/src/main/java/com/rajat/pdfviewer/PdfRendererView.kt
Labels: size/XS

#209 Create notify-resolved.yml
  .github/workflows/notify-resolved.yml
Labels: size/M
